### ISSUE TITLE
Устранить дублирование роутов

### ISSUE THREAD

**Issue by Lindemann66** [Ketzenkrad/Rails-Full#2]
https://github.com/Ketzenkrad/Rails-Full/blob/Rails-%D1%82%D0%B5%D1%81%D1%82%D1%8B/blog/config/routes.rb#L2

Здесь почему-то дублирование роутов

**Comment by UntestedFrom43** [comment]
Да, проглядел этот момент почему-то в финале. Хотя изначально я их прописывал вручную. Буду править.

**Comment by UntestedFrom43** [comment]
https://github.com/Ketzenkrad/Rails-Full/pull/3
Дубликаты пока удалил только здесь. Вечером проверю на Ubuntu, не продублируются ли после удаления в main-папке и перезапуска рельсы.

**Comment by Lindemann66** [comment]
Все ок!:)
